SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Table structure for table `history`
--

DROP TABLE IF EXISTS `history`;
CREATE TABLE IF NOT EXISTS `history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STEAMID` varchar(75) NOT NULL DEFAULT '0',
  `POINTS` varchar(75) NOT NULL DEFAULT '0',
  `ONTIME` varchar(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
