SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Table structure for table `location`
--

DROP TABLE IF EXISTS `location`;
CREATE TABLE IF NOT EXISTS `location` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STEAMID` varchar(75) NOT NULL DEFAULT '0',
  `IP` varchar(75) NOT NULL DEFAULT '0',
  `COUNTRYCODE` varchar(10) NOT NULL DEFAULT '0',
  `COUNTRYNAME` varchar(250) NOT NULL DEFAULT '0',
  `CITYNAME` varchar(250) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=45 ;
